name: run docker

on:
  schedule:
    - cron: '0 5,18,22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache docker image
      id: cache-docker-image
      uses: actions/cache@v2
      with:
        path: '/tmp/path/cache'
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}
        
    - name: Install node dependencies
      run: yarn install --frozen-lockfile

    - name: docker-compose up
      run: docker-compose up
      env:
        TWITTER_CONSUME_KEY: ${{ secrets.TWITTER_CONSUME_KEY }}
        TWITEER_CONSUME_SECRET: ${{ secrets.TWITEER_CONSUME_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
